// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxotdoUvNvOS89qZ2LBZVA7wiwmsTuuvM',
    appId: '1:706588350201:web:6485d7aecf2a2524b1b428',
    messagingSenderId: '706588350201',
    projectId: 'fir-votingappexample',
    authDomain: 'fir-votingappexample.firebaseapp.com',
    storageBucket: 'fir-votingappexample.appspot.com',
    measurementId: 'G-TBJJP5EJZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6rr3DRkx3rw06wNRKQkYtZnQSjxUbtHA',
    appId: '1:706588350201:android:d2288c319ceae7adb1b428',
    messagingSenderId: '706588350201',
    projectId: 'fir-votingappexample',
    storageBucket: 'fir-votingappexample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwJcTwg9JANxmx631YwiZ7Y8HkRHiZNys',
    appId: '1:706588350201:ios:42ffd9596e3dd0bbb1b428',
    messagingSenderId: '706588350201',
    projectId: 'fir-votingappexample',
    storageBucket: 'fir-votingappexample.appspot.com',
    iosBundleId: 'com.example.firebaseVotingAppExample',
  );
}
